export enum CompanyType {
  PROPRIETORSHIP = 'PROPRIETORSHIP',
  PARTNERSHIP = 'PARTNERSHIP',
  PRIVATE_LIMITED_COMPANY = 'PRIVATE_LIMITED_COMPANY',
  PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY',
  PUBLIC_SECTOR_UNDERTAKING = 'PUBLIC_SECTOR_UNDERTAKING',
  PRIVATE_SECTOR_UNDERTAKING = 'PRIVATE_SECTOR_UNDERTAKING',
  CO_OPERATIVE_SOCIETIES = 'CO_OPERATIVE_SOCIETIES',
  TRUST_SOCIETY_ASSOCIATION_OF_PERSONS = 'TRUST_SOCIETY_ASSOCIATION_OF_PERSONS',
  GOVERNMENT_ORGANIZATIONS = 'GOVERNMENT_ORGANIZATIONS',
}
